on:
  push:
    branches: [ main, staging ] # Add in branches as necessary 
  pull_request:
    branches: [ main, staging] # Add in branches as necessary

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs ( build and deploy )
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        node-version: "15"
        
    - name: NPM Install
      run: npm install
      

    - name: Build + Export
      run: npm run build
      
    - name: zip build result
      run: tar -czvf build.tar.gz build
    - name: archive zip
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build.tar.gz

## Success of this step insures no issue with build directory


  deploy:
    needs: 
      - build
    runs-on: ubuntu-latest
    
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: extract build
        run: tar -xzvf build.tar.gz

      - name: Deploying to Netlify @ 
        if: github.ref == 'refs/heads/main'
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.AUTH_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build'
          comment-on-commit: true
      
          
      - name: Staging Run Complete - No Deploy
        if: github.ref == 'refs/heads/staging'
        run: echo " Staging Build Check Complete " 
